engines:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
    checks:
      Naming/ShortMethodName:
        enabled: false
      Naming/LongVariable:
        enabled: false
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
      file_extensions: "php"
exclude_paths:
- tests/
