# Component: UCSDMath Project
# Date: 2016-04-21
# File: .scrutinizer.yml
# -----------------------------------
before_commands:
    - "composer install --dev --prefer-source"
tools:
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src"]
    php_cs_fixer:
        enabled: true
        config:
          level: psr2
        filter:
            excluded_paths: ["src/dev/*","tests/*","vendor/*"]
            paths: ["src/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["src/dev/*","tests/*","vendor/*"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
        config:
            rulesets:
                - codesize
                - unusedcode
                - naming
                - design
    php_pdepend:
        enabled: true
        excluded_dirs: ["src/dev","tests","vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]
    php_code_coverage:
        enabled: false
    sensiolabs_security_checker:
        enabled: true
    php_analyzer:
        enabled: true
        config:
            checkstyle:
                enabled: true
                naming:
                    enabled: true
                    property_name: ^[_a-zA-Z][a-zA-Z0-9_]*$ # Allow underscores & caps
                    method_name: ^(?:[_a-zA-Z]|__)[a-zA-Z0-9_]*$ # Allow underscores & caps
                    parameter_name: ^[a-z][a-zA-Z0-9_]*$ # Allow underscores
                    local_variable: ^[a-zA-Z][a-zA-Z0-9_]*$ # Allow underscores & caps
checks:
    php:
        code_rating: true
        duplication: true
        fix_doc_comments: false
        remove_php_closing_tag: false
        remove_extra_empty_lines: false
        remove_trailing_whitespace: false
        fix_use_statements:
            remove_unused: false
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
filter:
    excluded_paths: ["tests/*"]
