tools:
    php_code_coverage: true
    sensiolabs_security_checker: true
    php_mess_detector: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2

    # Runs Scrutinizer's PHP Analyzer Tool
    php_analyzer:
        enabled: true
        filter:
            excluded_paths:
                - dev/*
                - test/*
                - vendor/*

    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests, dev]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests, dev]

checks:
    php:
        code_rating: true
        duplication: true
        fix_doc_comments: false
        remove_php_closing_tag: false
        remove_extra_empty_lines: false
        remove_trailing_whitespace: false
filter:
    paths: [src/*]
    excluded_paths:
        - tests/*
        - dev/*
