# Component: UCSDMath Project
# Date: 2016-04-20
# -----------------------------------
build:
    environment:
        php:
            version: 7.0

before_commands:
    - composer install --prefer-source --dev

tools:

    # PHP Code Sniffer
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src']

    # PHP CS Fixer (http://http://cs.sensiolabs.org/).
    php_cs_fixer:
        enabled: true
        config:
          level: psr2

    # PHP Mess Detector (http://phpmd.org).
    php_mess_detector:
        enabled: true

    # PHP Analyzer
    php_analyzer:
        enabled: true

    # PHP Code Coverage
    php_code_coverage:
        enabled: false

    # Security Advisory Checker
    sensiolabs_security_checker:
        enabled: true

    # Scrutinizers PHP Analyzer Tool
    php_analyzer:
        enabled: true
        config:
            checkstyle:
                enabled: true
                naming:
                    enabled: true
                    property_name: ^[_a-zA-Z][a-zA-Z0-9_]*$ # Allow underscores & caps
                    method_name: ^(?:[_a-zA-Z]|__)[a-zA-Z0-9_]*$ # Allow underscores & caps
                    parameter_name: ^[a-z][a-zA-Z0-9_]*$ # Allow underscores
                    local_variable: ^[a-zA-Z][a-zA-Z0-9_]*$ # Allow underscores & caps
checks:
    php:
        code_rating: true
        duplication: true
        fix_doc_comments: false
        remove_php_closing_tag: false
        remove_extra_empty_lines: false
        remove_trailing_whitespace: false
        fix_use_statements:
            remove_unused: false
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
filter:
    excluded_paths:
        - 'tests/*'
        - 'dev/*'
        - 'dev/*'

