# Framework Component: ucsdmath/
# File: .scrutinizer.yml
# -----------------------------------
build:
    environment:
        php:
            version: 7.0
checks:
    php:
        code_rating: true
        duplication: true
        remove_php_closing_tag: false
filter:
    excluded_paths:
        - tests/*
        - dev/*
tools:
    php_analyzer: true
    php_code_coverage: false
    php_code_sniffer:
        config:
            standard: PSR2
